CREATE TABLE REGISTROS (
    id INT PRIMARY KEY AUTO_INCREMENT,
    nome VARCHAR(255) NOT NULL,
    telefone INT NOT NULL,
    deficiencia VARCHAR(255),
    data_nascimento DATE NOT NULL,
    adicionado_por INT NOT NULL REFERENCES USUARIOS(id),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
)